### ISSUE TITLE
Podfile won't update to version 1.7.0

### ISSUE THREAD

**Issue by muzoman** [SwiftyBeaver/SwiftyBeaver#322] opened 2019-03-26 21:26 UTC
My podfiles won't pull the latest 1.7.0 version - only version 1.6.2 my test podfile is:

platform :ios, '10.0'

target 'OCCO' do
  use_frameworks!

pod 'SwiftyBeaver'
end

Any idea why I can't pull the latest?

**Comment by agordeev** [comment] 2019-03-27 04:37
The latest version wasn't pushed to Cocoapods repository for unknown reason :-/

**Comment by skreutzberger** [comment] 2019-03-27 09:17
We had an issue uploading the latest version to Cocoapods. The issue is fixed now and Cocoapods should serve version 1.7.0. Thanks for reporting!

Good to know: if you have similar issues later on or with other frameworks then try this:
` pod 'SwiftyBeaver', :git => 'https://github.com/SwiftyBeaver/SwiftyBeaver.git', :branch => 'master', :tag => ‘1.7.0'`

**Closed by skreutzberger** 2019-03-27 09:17 UTC
