### ISSUE TITLE
Crash on formatting Date within message

### ISSUE THREAD

**Issue by mkaminow** [SwiftyBeaver/SwiftyBeaver#346] opened 2019-08-18 18:22 UTC
I'm using version 1.7.0 of SwiftyBeaver and have not changed versions or made any changes to my apps message formatting recently. Yet in my last release my user's started getting the following crash.

![Screen Shot 2019-08-18 at 2 19 56 PM](https://user-images.githubusercontent.com/8104175/63228602-5deb5c80-c1c3-11e9-8f6a-08da67dce353.png)

My message formatting string looks like this.
```
static func setup() {
        let console = ConsoleDestination()
        console.format = "$DHH:mm:ss.SSS$d $C$L$c $N.$F:$l - $M"
        LogUtils.logger.removeAllDestinations()
        LogUtils.logger.addDestination(console)
    }
```

**Comment by skreutzberger** [comment] 2019-08-19 07:36
What iOS version does your user have? The line involved is ` let dateStr = formatter.string(from: Date())` and formatter is a class property `let formatter = DateFormatter()` so nothing unusual there. That logic exists since the beginning and is compatible with the latest Swift versions. 

Can you reproduce the crash?

**Comment by VladimirHorky86** [comment] 2019-08-19 11:20
It happens on tvOS 11 and 12. I can not reproduce it personally, but users have a lot of crashes in the past 5 days.

**Comment by skreutzberger** [comment] 2019-08-19 11:24
Hmm, that is pretty weird since we did not change anything at all and it does not seem to be an issue of a very new beta version of an Apple OS. Please keep monitored and maybe try to reproduce it. Thanks!

**Comment by VladimirHorky86** [comment] 2019-08-19 11:40
Thank you for the information. We'll keep track it.

**Comment by skreutzberger** [comment] 2019-08-19 11:54
closing it for now, please keep on reporting

**Closed by skreutzberger** 2019-08-19 11:54 UTC

**Comment by VladimirHorky86** [comment] 2019-09-25 09:16
So it happened to me finally.
We call function setup() in AppDelegate.application(_:didFinishLaunchingWithOptions:) and it crash when we try to set `format`. You can see it on the screenshot.
![Screenshot 2019-09-25 at 11 02 54](https://user-images.githubusercontent.com/29255888/65586295-3c308280-df84-11e9-9930-336453bcb7f0.png)
btw. We know that's the default format string, but it would be great to have a possibility to change it.

**Comment by skreutzberger** [comment] 2019-09-25 14:04
Thank you for sharing that info!
Does it still crash if you tried the following:

1. remove the `removeAllDestination(...)` line?
2. use a different format string? Maybe your logger setup does not like one of the formatter properties?

**Comment by VladimirHorky86** [comment] 2019-09-26 08:21
`removeAllDestination(...)` is not called, because it crashes before that line.
I tried to change the format string, but it didn't help. Because we use the same format string like it's default so we removed that line. It's not possible to change the format string for us, it's crashing all the time with Xcode 11.
Thanks for everything.

**Comment by skreutzberger** [comment] 2019-09-26 08:38
Ah it is crashing on Xcode 11, maybe that is the reason? Does it also crash on Xcode 10?

**Comment by skreutzberger** [comment] 2019-09-26 09:15
Tomorrow we will release a new version which has full Xcode 11 and iOS 13 support. It will use the code that was hosted on the `xcode11-beta` branch. Maybe that will help to fix the crash.

**Comment by VladimirHorky86** [comment] 2019-09-26 09:51
We came here because some users have experienced a crash in the same line - build provided by Xcode 10. It started crashing every time with Xcode 11. 
We are good now because we don't need to change the formatting.
