### ISSUE TITLE
fatal error: Negative value is not representable

### ISSUE THREAD

**Issue by Narsail** [SwiftyBeaver/SwiftyBeaver#240] opened 2017-08-04 20:53 UTC
Platform: Apple Watch
watchOS: 4.0 Beta 2
Swift: 3.2

I have an interesting error for you:

fatal error: Negative value is not representable

**Thread**:
```
#0	0x00a89618 in specialized _fatalErrorMessage(_:_:file:line:flags:) ()
#1	0x00a93f10 in specialized String.Index.init(encodedOffset:) ()
#2	0x00a07e60 in protocol witness for _IndexableBase.endIndex.getter in conformance String.CharacterView ()
#3	0x008cdd70 in Collection.count.getter ()
#4	0x007fea68 in SBPlatformDestination.sendNow() at /Users/davidmoeller/Developer/Evomo/Evomo/Pods/SwiftyBeaver/Sources/SBPlatformDestination.swift:245
#5	0x007fdea0 in SBPlatformDestination.send(_:msg:thread:file:function:line:context:) at /Users/davidmoeller/Developer/Evomo/Evomo/Pods/SwiftyBeaver/Sources/SBPlatformDestination.swift:192
#6	0x0080a750 in closure #1 in static SwiftyBeaver.dispatch_send(level:message:thread:file:function:line:context:) at /Users/davidmoeller/Developer/Evomo/Evomo/Pods/SwiftyBeaver/Sources/SwiftyBeaver.swift:141
#7	0x0080ae88 in partial apply for closure #1 in static SwiftyBeaver.dispatch_send(level:message:thread:file:function:line:context:) ()
#8	0x0080a7dc in thunk for @callee_owned () -> () ()
#9	0x1aea4230 in _dispatch_call_block_and_release ()
#10	0x1aea420c in _dispatch_client_callout ()
#11	0x1aeb17ec in _dispatch_queue_serial_drain$VARIANT$mp ()
#12	0x1aeb20c4 in _dispatch_queue_invoke$VARIANT$mp ()
#13	0x1aeb2a84 in _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp ()
#14	0x1aeb9f02 in _dispatch_workloop_worker_thread$VARIANT$mp ()
#15	0x1b106558 in _pthread_wqthread ()
#16	0x1b1061d0 in start_wqthread ()
```

**Breakpoint**:

```
libswiftCore.dylib`function signature specialization <preserving fragile attribute, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage(Swift.StaticString, Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never:
    0xa8959c <+0>:   push   {r4, r5, r6, r7, lr}
    0xa895a0 <+4>:   add    r7, sp, #12
    0xa895a4 <+8>:   str    r8, [sp, #-0x4]!
    0xa895a8 <+12>:  sub    sp, sp, #8
    0xa895ac <+16>:  mov    r5, r0
    0xa895b0 <+20>:  movw   r0, #0xb8bc
    0xa895b4 <+24>:  movt   r0, #0x18
    0xa895b8 <+28>:  mov    r8, r2
    0xa895bc <+32>:  add    r0, pc, r0
    0xa895c0 <+36>:  mov    r6, r1
    0xa895c4 <+40>:  add    r0, r0, #8
    0xa895c8 <+44>:  mov    r1, #28
    0xa895cc <+48>:  mov    r2, #3
    0xa895d0 <+52>:  mov    r4, r3
    0xa895d4 <+56>:  bl     0xaab528                  ; swift_rt_swift_allocObject
    0xa895d8 <+60>:  movw   r9, #0xb524
    0xa895dc <+64>:  ldr    r1, [r7, #0x10]
    0xa895e0 <+68>:  ldr    r2, [r7, #0xc]
    0xa895e4 <+72>:  movt   r9, #0xb
    0xa895e8 <+76>:  ldr    r3, [r7, #0x8]
    0xa895ec <+80>:  add    r9, pc, r9
    0xa895f0 <+84>:  str    r4, [r0, #0xc]
    0xa895f4 <+88>:  str    r3, [r0, #0x10]
    0xa895f8 <+92>:  mov    r3, r8
    0xa895fc <+96>:  strb   r2, [r0, #0x14]
    0xa89600 <+100>: mov    r2, r6
    0xa89604 <+104>: str    r1, [r0, #0x18]
    0xa89608 <+108>: mov    r1, r5
    0xa8960c <+112>: str    r0, [sp, #0x4]
    0xa89610 <+116>: str    r9, [sp]
    0xa89614 <+120>: bl     0x8ba87c                  ; function signature specialization <preserving fragile attribute, Arg[1] = [Closure Propagated : reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()), Argument Types : [@callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()]> of generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer<A>((Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A
->  0xa89618 <+124>: trap   
```

**Comment by skreutzberger** [comment] 2017-08-07 16:23
Thanks for reporting! That can be caused by watchOS 4 Beta. In 1 week we are releasing a new version with official support for the latest Swift 4 and Apple Betas so the issue should be fixed.

You can already have a sneek peak into the new release here: https://github.com/SwiftyBeaver/SwiftyBeaver/pull/241

**Closed by skreutzberger** 2017-08-07 16:23 UTC
