### ISSUE TITLE
xcodebuild fails on Xcode 12.1 (12A7403) with SwiftyBeaver as a dependency

### ISSUE THREAD

**Issue by andylamp** [SwiftyBeaver/SwiftyBeaver#434] opened 2020-11-08 22:26 UTC
First of, thanks for the amazing package 😄! Now, installing `SwiftyBeaver` using the Swift Package manager, as is shown within `README` fails when invoked through the command line. However, if the project is compiled from within Xcode everything works as expected.

The steps to reproduce this are fairly simple:

 1. Use Xcode 12.1 (12A7403),
 2. Create a new Swift App,
 3. Add `SwiftyBeaver` using the Swift Package Manager,
 4.  Do the following in the `@main` - that's the only thing I changed in the whole code generated.

```swift
import SwiftUI
import SwiftyBeaver

let log = SwiftyBeaver.self
let console = ConsoleDestination()  // log to Xcode Console

@main
struct testpackageApp: App {
    let persistenceController = PersistenceController.shared

    var body: some Scene {
        WindowGroup {
            ContentView()
              .environment(\.managedObjectContext, persistenceController.container.viewContext).onAppear {
                log.addDestination(console)
                
                log.info("an example to show it has loaded")
              }
        }
    }
}
```

If I compile within Xcode IDE (even the use of the simulator) everything works as expected; should I go to the command line and type in the directory of the project `xcodebuild` then it fails with:

```
/Users/andylamp/Desktop/testpackage/testpackage/testpackageApp.swift:10:8: error: no such module 'SwiftyBeaver'
import SwiftyBeaver
       ^

** BUILD FAILED **
```

Removing `SwiftyBeaver` and adding another dependency seems to not generate the same issue (I tried with `Alamofire`).

Hope this helps to resolve the issue!

**Comment by skreutzberger** [comment] 2020-11-09 10:57
thanks for the example and explanation. so it seems to be an `SPM` issue since it works after that. Weird. Let's see if other contributors have a solution for it.

**Comment by andylamp** [comment] 2020-11-09 15:05
@skreutzberger just wondering - were you able to reproduce it locally on your end? I tried on two different machines and given the steps above I could reproduce it. My conjecture also is that the problem lies with `SPM` itself.

**Comment by skreutzberger** [comment] 2020-11-10 07:52
yes, I could reproduce it. I guess it is an SPM issue.

**Comment by skreutzberger** [comment] 2020-11-10 07:52
I am closing the ticket for now until more people do report it

**Closed by skreutzberger** 2020-11-10 07:52 UTC

**Comment by andylamp** [comment] 2020-11-10 08:30
hmm, is there any workaround with this? this is kind of important as it breaks CI pipelines...

**Comment by andylamp** [comment] 2020-11-13 21:02
@skreutzberger just to update this - the issue still happens on 12.2 Xcode which was released recently; and is the latest version available.

**Comment by delvinwidjaja** [comment] 2021-02-12 13:56
Hi @andylamp , did you manage to solve this issue? I'm having the same problem with SPM & SwiftyBeaver

**Comment by andylamp** [comment] 2021-02-12 14:54
@delvinwidjaja as far as I can tell the issue is still present, @skreutzberger said he'd ignore it until it became a bigger issue (i.e.: more people reported it). 

Hope this helps.

**Comment by IsaiahJTurner** [comment] 2021-03-30 05:24
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment] 2021-03-30 06:42
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.

**Comment by reececomo** [comment] 2021-04-18 10:53
@skreutzberger was broken in our CI environment for us too.

Like @andylamp mentioned, all our other Swift Packages work fine, so I suspect there might be some package setting that causes this?

Unfortunately we had to remove SwiftyBeaver 😦 in the meantime, would love to switch back at some point.

```
/Source/Utilities/Log.swift:1:8: error: no such module 'SwiftyBeaver'
import SwiftyBeaver
       ^


** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler

**Comment by mpawlo** [comment] 2021-07-15 08:41
Problem still valid on Xcode 12.5.1
