### ISSUE TITLE
Problem with emoji in console

### ISSUE THREAD

**Issue by pasevin** [SwiftyBeaver/SwiftyBeaver#175] opened 2017-02-08 09:02 UTC
I am using Xcode 8 and Swift 3, but still getting emojis with unwanted artefacts: ``` \360\237\222💚 DEBUG:...```

My setup:

```
let console = ConsoleDestination()
console.format = "$Dyyyy-MM-dd HH:mm:ss.SSS$d $C$L$c: $N.$F:$l - $M"
log.addDestination(console)
```

I tried removing ```$C``` and ```$c``` variables, but then console doesn't show emoji at all.

I tried as well using:

```
console.levelString.verbose = "💜 VERBOSE"
console.levelString.debug = "💚 DEBUG"
console.levelString.info = "💙 INFO"
console.levelString.warning = "💛 WARNING"
console.levelString.error = "❤️ ERROR"
```

Same result. Any ideas? I'm on v.1.1.1

**Comment by skreutzberger** [comment] 2017-02-08 11:47
Does it always happen or just randomly?

**Comment by LordNali** [comment] 2017-02-08 12:01
I had the same Issue some days ago - but I couldn't reproduce it.

**Comment by pasevin** [comment] 2017-02-08 23:08
It happens randomly, but always on this line: ```log.debug("[\(method.rawValue)] \(url)")```

Output:

```
2017-02-08 15:05:35.163 \360\237\360\237\360\237\222💚 DEBUG: Network.request():149 - GET https://app.myapp.com/foo/bar/3
```

**Comment by LordNali** [comment] 2017-02-09 10:54
I found "my" line to:

`11:53:00.048 \360\237\222💙 INFO ...`

**Comment by skreutzberger** [comment] 2017-02-09 15:55
It seems Xcode’s console sometimes just has issues correctly displaying certain UTF8 characters. It is interesting that it prints the emoji but still adds some stuff. Maybe one of the next Xcode minor versions will fix the issue. For now I will close the issue since it is not caused by SwiftyBeaver but our good(?), old friend Xcode :D

**Closed by skreutzberger** 2017-02-09 15:55 UTC
